# Generated by Django 3.0.6 on 2021-07-19 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_mnagament_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='staffs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
